In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [2]:
d=load_boston()
X=d.data
y=d.target

In [37]:
class CustomLinearRegression:
    def fit(self,X,y):
        self.__mean=X.mean(axis=0)
        self.__std=X.std(axis=0)
        X=(X-self.__mean)/self.__std
        
        X_mod=np.hstack([np.ones((X.shape[0],1)),X])
        y_mod=y.reshape(-1,1)
        
        self.first=np.linalg.inv(np.dot(X_mod.T,X_mod))
        self.second=np.dot(X_mod.T,y_mod)
        self.theta_=np.dot(self.first,self.second)
        
    def hypo(self,X):
        return (np.dot(X,self.theta_))
    
    def predict(self,X):
        X_mod=(X-self.__mean)/self.__std
        X_mod=np.hstack([np.ones((X_mod.shape[0],1)),X_mod])
        y_hypo=self.hypo(X_mod)
        return y_hypo.flatten()

In [38]:
model=CustomLinearRegression()
model.fit(X,y)

In [39]:
model.predict(X[:10])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211])

In [40]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [41]:
model.theta_

array([[ 2.25328063e+01],
       [-9.28146064e-01],
       [ 1.08156863e+00],
       [ 1.40899997e-01],
       [ 6.81739725e-01],
       [-2.05671827e+00],
       [ 2.67423017e+00],
       [ 1.94660717e-02],
       [-3.10404426e+00],
       [ 2.66221764e+00],
       [-2.07678168e+00],
       [-2.06060666e+00],
       [ 8.49268418e-01],
       [-3.74362713e+00]])

In [43]:
model.first.shape

(14, 14)

In [44]:
model.second.shape

(14, 1)